import React, {Component} from 'react';
import {BrowserRouter as Router, Switch, Link, Route} from 'react-router-dom';
import Navbar from './../Containers/Navbar'
import {AppBar, Toolbar, Paper, Typography, styled, Button} from "@material-ui/core";
import {ListItem, Fab, ListSubheader, ListItemAvatar, ListItemText, List, Avatar} from "@material-ui/core";
import {Menu, Add} from "@material-ui/icons";

class Welcome extends Component{
    constructor() {
        super();
        this.state = {};
    }

    render() {
        const messages = [
            {
                id: 1,
                primary: 'Brunch this week?',
                secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
                person: '/static/images/avatar/5.jpg',
            },
            {
                id: 2,
                primary: 'Birthday Gift',
                secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
                person: '/static/images/avatar/1.jpg',
            },
            {
                id: 3,
                primary: 'Recipe to try',
                secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
                person: '/static/images/avatar/2.jpg',
            },
            {
                id: 4,
                primary: 'Yes!',
                secondary: 'I have the tickets to the ReactConf for this year.',
                person: '/static/images/avatar/3.jpg',
            },
            {
                id: 5,
                primary: "Doctor's Appointment",
                secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
                person: '/static/images/avatar/4.jpg',
            },
            {
                id: 6,
                primary: 'Discussion',
                secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
                person: '/static/images/avatar/5.jpg',
            },
            {
                id: 7,
                primary: 'Summer BBQ',
                secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
                person: '/static/images/avatar/1.jpg',
            },
        ];

        const MyAppBar = styled(AppBar)({
            top: 'auto',
            bottom: 0,
        });

        const MyButton = styled(Button)({
            position: 'absolute',
            zIndex: 1,
            top: -30,
            left: 0,
            right: 0,
            margin: '0 auto',
        });

        return (
            <Router>
                <Navbar />
                <Paper square>
                    <Typography variant="h1" gutterBottom>
                        Welcome!
                    </Typography>
                    <List >
                        {messages.map(({ id, primary, secondary, person }) => (
                            <React.Fragment key={id}>
                                {id === 1 && <ListSubheader>Today</ListSubheader>}
                                {id === 3 && <ListSubheader>Yesterday</ListSubheader>}
                                <ListItem button>
                                    <ListItemAvatar>
                                        <Avatar alt="Profile Picture" src={person} />
                                    </ListItemAvatar>
                                    <ListItemText primary={primary} secondary={secondary} />
                                </ListItem>
                            </React.Fragment>
                        ))}
                    </List>
                </Paper>
                <MyAppBar position="fixed" color="primary">
                    <Toolbar>
                        <MyButton color="secondary" aria-label="register">
                            <Typography variant='button' color={'inherit'}>Register</Typography>
                        </MyButton>
                        <div />
                    </Toolbar>
                </MyAppBar>
            </Router>
        )
    }
}

export default Welcome;